local Color, colors, Group, groups, styles = require("colorbuddy").setup()

Color.new("white", "#f2e5bc")
Color.new("bgnd", "#171818")
Color.new("bgnd_c", "#282828")
Color.new("red", "#cc6666")
Color.new("pink", "#fef601")
Color.new("green", "#99cc99")
Color.new("yellow", "#f8fe7a")
Color.new("blue", "#81a2be")
Color.new("aqua", "#8ec07c")
Color.new("cyan", "#8abeb7")
Color.new("purple", "#8e6fbd")
Color.new("violet", "#b294bb")
Color.new("orange", "#de935f")
Color.new("brown", "#a3685a")

Color.new("seagreen", "#698b69")
Color.new("turquoise", "#698b69")

Group.new("Normal", colors.none, colors.bgnd, nil)
Group.new("Cursor", colors.yellow, colors.yellow, nil)
Group.new("CursorLine", colors.none, colors.bgnd_c, nil)
Group.new("cursorLineNR", colors.yellow, colors.none, styles.NONE)
Group.new("LineNR", colors.none, colors.bgnd_c, styles.NONE)
Group.new("Visual", colors.none, colors.bgnd_c, styles.NONE)
